"""Hand strength helpers shared by the LLM prompt and the offline bot.

Two jobs:

* :func:`preflop_strength` -- a 0..1 percentile for any two hole cards, built on
  a static ordering of all 169 starting hands (Chen-formula scoring).  0.0 is
  7-2 offsuit, 1.0 is pocket aces.
* :func:`postflop_strength` -- a 0..1 estimate from the made-hand category plus
  a little credit for draws.

The LLM does not *need* these numbers -- it reasons for itself -- but they give
it a calibrated anchor, and the offline bot needs them to behave sensibly.
"""

from __future__ import annotations

from functools import lru_cache

from .cards import Card, _score_of_codes, evaluate

RANK_CHARS = "23456789TJQKA"

#: The 52 cards, built once.  Equity sampling reads this far more often than it
#: builds anything, so re-creating it per trial was pure overhead.
_DECK_CACHE: tuple[Card, ...] = tuple(
    Card(rank, suit) for rank in range(13) for suit in range(4)
)

# --------------------------------------------------------------------------
# Chen-formula-ish preflop scoring
# --------------------------------------------------------------------------
_HIGH_CARD_VALUE = {
    "A": 10.0,
    "K": 8.0,
    "Q": 7.0,
    "J": 6.0,
    "T": 5.0,
    "9": 4.5,
    "8": 4.0,
    "7": 3.5,
    "6": 3.0,
    "5": 2.5,
    "4": 2.0,
    "3": 1.5,
    "2": 1.0,
}


def _chen_score(high: str, low: str, suited: bool, pair: bool) -> float:
    if pair:
        # Pairs: double the high-card value, minimum 5.
        return max(5.0, _HIGH_CARD_VALUE[high] * 2)

    score = _HIGH_CARD_VALUE[high]
    if suited:
        score += 2.0

    gap = abs(RANK_CHARS.index(high) - RANK_CHARS.index(low)) - 1
    if gap == 1:
        score -= 1.0
    elif gap == 2:
        score -= 2.0
    elif gap == 3:
        score -= 4.0
    elif gap >= 4:
        score -= 5.0

    # Straight bonuses.
    if gap <= 1 and RANK_CHARS.index(high) < RANK_CHARS.index("Q"):
        score += 1.0

    # Round half points up, per the original formula.
    return float(int(score + 0.5)) if score >= 0 else float(-int(-score + 0.5))


@lru_cache(maxsize=1)
def _equity_lookup() -> dict[str, float]:
    """Map a hand token (``"AKs"``/``"72o"``/``"QQ"``) to a 0..1 percentile.

    Sourced from :data:`EQUITY_ORDER`, generated by Monte-Carlo all-in equity
    (see ``tools/gen_preflop_ranking.py``).  Strongest is 1.0, weakest is 0.0.
    """
    total = len(EQUITY_ORDER)
    return {
        token: (total - 1 - index) / (total - 1)
        for index, token in enumerate(EQUITY_ORDER)
    }


def hand_token(hole: list[Card]) -> str | None:
    """Canonical token for two hole cards, e.g. ``"AKs"``, ``"QQ"``, ``"72o"``."""
    if len(hole) != 2:
        return None
    a, b = hole
    if a.rank == b.rank:
        return RANK_CHARS[a.rank] * 2
    high_char = RANK_CHARS[max(a.rank, b.rank)]
    low_char = RANK_CHARS[min(a.rank, b.rank)]
    suffix = "s" if a.suit == b.suit else "o"
    return f"{high_char}{low_char}{suffix}"


def preflop_strength(hole: list[Card]) -> float:
    """0..1 percentile for two hole cards.  1.0 is AA, 0.0 is 32o."""
    token = hand_token(hole)
    if token is None:
        return 0.0
    return _equity_lookup().get(token, 0.0)


# --------------------------------------------------------------------------
# Post-flop strength
# --------------------------------------------------------------------------
# Baseline percentile by made-hand category, refined by how strong the top of
# the hand is.  These are deliberately conservative: one pair is usually not a
# monster multiway.  The spacing keeps the categories strictly ordered after the
# top-rank anchor is applied (see tests/test_strength.py).
_CATEGORY_BASE = {
    "High Card": 0.08,
    "One Pair": 0.36,
    "Two Pair": 0.60,
    "Three of a Kind": 0.76,
    "Straight": 0.86,
    "Flush": 0.93,
    "Full House": 0.965,
    "Four of a Kind": 0.99,
    "Straight Flush": 0.995,
    "Royal Flush": 1.0,
}


def _draw_bonus(hole: list[Card], board: list[Card]) -> float:
    """Small credit for flush and open-ended straight draws."""
    if len(board) < 3 or not hole:
        return 0.0
    bonus = 0.0
    cards = hole + board
    # Four to a flush, with at least one hole card contributing.
    for suit in range(4):
        suited = [c for c in cards if c.suit == suit]
        if len(suited) == 4 and any(c.suit == suit for c in hole):
            bonus += 0.07
            break
    # Four to a straight over a five-rank span.
    ranks = sorted({c.rank for c in cards})
    if 12 in ranks:
        ranks = ranks + [-1]  # ace plays low
    for index in range(len(ranks) - 3):
        window = ranks[index : index + 4]
        if window[-1] - window[0] == 3:
            bonus += 0.05
            break
    return bonus


def postflop_strength(hole: list[Card], board: list[Card]) -> float:
    """0..1 estimate of how good the current made hand is."""
    if len(board) < 3:
        return preflop_strength(hole)
    result = evaluate(hole + board)
    base = _CATEGORY_BASE[result.name]
    # Nudge upward/downward by the strength of the five cards that make it.
    from .cards import best_five

    _, best = best_five(hole + board)
    top_rank = max(card.rank for card in best) / 12 if best else 0.0
    anchor = 0.015 * top_rank
    return min(1.0, base + anchor + _draw_bonus(hole, board))


def strength(hole: list[Card], board: list[Card]) -> float:
    return postflop_strength(hole, board) if len(board) >= 3 else preflop_strength(hole)


# --------------------------------------------------------------------------
# Equity against a range
# --------------------------------------------------------------------------
# The functions above answer "how good is this hand?", which is the right anchor
# for a prompt but the *wrong* input for a pot-odds decision.  A gutshot with two
# overcards is a weak *made* hand (0.08 by category) yet frequently has 30-40%
# equity, and folding it when the price is 20:1 is a blunder no player makes.
#
# Equity is measured against the range an opponent could actually hold, not a
# random hand: against a random hand almost everything has ~50%, which would
# make every pot-odds call look correct.
_STANDARD_RANGE_RANK = 0.45   # the better ~45% of starting hands
_TIGHT_RANGE_RANK = 0.22      # a raise represents roughly the better fifth

# Bounds on the work per lookup.  A pot-odds decision needs only a rough equity:
# the caller compares it against a price with a 15% safety margin, and being
# wrong by 3 points almost never changes whether the call is +EV.  Precision
# costs real time -- a whole game's runtime was dominated by this loop -- so the
# trial count is set for decisions, not for a published number.  ~260 trials
# puts the standard error near 3%.
_MIN_TRIALS = 120
_MAX_TRIALS = 260
_TARGET_STDERR = 0.031


@lru_cache(maxsize=4096)
def _range_tokens(rank: float) -> tuple[str, ...]:
    """Starting hands at or above ``rank`` percentile, strongest first."""
    total = len(EQUITY_ORDER)
    keep = max(4, int(total * max(0.01, min(1.0, 1.0 - rank))))
    return EQUITY_ORDER[:keep]


@lru_cache(maxsize=16384)
def _equity_cached(hole_codes: tuple[str, ...], board_codes: tuple[str, ...],
                   rank: float) -> float:
    """Monte-Carlo equity, memoised on the exact cards and range.

    The inner loop is written for throughput rather than clarity, because this
    runs once per post-flop decision and is easy to make 20x slower by accident:
    re-filtering the deck per trial, or scanning a suit to find a rank, dominated
    the actual hand evaluation.  Cards are indexed once into rank/suit tables and
    the runout is drawn directly instead.
    """
    import random

    hole = [Card.from_str(code) for code in hole_codes]
    board = [Card.from_str(code) for code in board_codes]
    if len(hole) != 2:
        return 0.0

    known = {c.code for c in hole} | {c.code for c in board}
    tokens = _range_tokens(rank)
    rng = random.Random(hash((hole_codes, board_codes, rank)) & 0xFFFFFFFF)

    # Index the live cards once: by (rank, suit) for exact lookups, and by rank
    # for picking a pair, and by suit holding the rank->card map.
    live = [c for c in _DECK_CACHE if c.code not in known]
    by_suit: dict[int, dict[int, Card]] = {}
    by_rank: dict[int, list[Card]] = {}
    for card in live:
        by_suit.setdefault(card.suit, {})[card.rank] = card
        by_rank.setdefault(card.rank, []).append(card)
    suits = list(by_suit)
    need_runout = 5 - len(board)

    def draw_opponent() -> tuple[Card, Card] | None:
        for _ in range(6):
            token = tokens[rng.randrange(len(tokens))]
            if len(token) == 2:
                # A pair: both cards share the rank we want.
                rank_index = RANK_CHARS.index(token[0])
                candidates = by_rank.get(rank_index)
                if candidates and len(candidates) >= 2:
                    return candidates[0], candidates[1]
                continue
            high = RANK_CHARS.index(token[0])
            low = RANK_CHARS.index(token[1])
            if token[2] == "s":
                suit = suits[rng.randrange(len(suits))]
                column = by_suit[suit]
                first, second = column.get(high), column.get(low)
                if first is not None and second is not None:
                    return first, second
                continue
            suit_a = suits[rng.randrange(len(suits))]
            suit_b = suits[rng.randrange(len(suits))]
            if suit_a == suit_b:
                continue
            first, second = by_suit[suit_a].get(high), by_suit[suit_b].get(low)
            if first is not None and second is not None:
                return first, second
        return None

    wins = ties = 0
    trials = 0
    # Hoisted: these do not change between trials, and rebuilding them per trial
    # was a measurable share of the work.
    hole_codes_sorted = tuple(sorted(c.code for c in hole))
    board_codes_sorted = tuple(c.code for c in board)
    score = _score_of_codes
    while trials < _MAX_TRIALS:
        for _ in range(60):
            opponent = draw_opponent()
            if opponent is None:
                continue
            # Draw the runout from what is left, without rebuilding a deck list.
            blocked = known | {opponent[0].code, opponent[1].code}
            runout: list[Card] = []
            while len(runout) < need_runout:
                card = live[rng.randrange(len(live))]
                if card.code not in blocked:
                    blocked.add(card.code)
                    runout.append(card)
            runout_codes = tuple(sorted(c.code for c in runout))
            final_board = board_codes_sorted + runout_codes

            mine = score(tuple(sorted(hole_codes_sorted + final_board)))
            theirs = score(tuple(sorted(
                (opponent[0].code, opponent[1].code) + final_board
            )))
            if mine > theirs:
                wins += 1
            elif mine == theirs:
                ties += 1
            trials += 1

        if trials >= _MIN_TRIALS:
            p = (wins + ties / 2) / trials
            if (p * (1 - p) / trials) ** 0.5 <= _TARGET_STDERR:
                break

    if not trials:
        return 0.0
    return (wins + ties / 2) / trials


@lru_cache(maxsize=1)
def _preflop_equity_table() -> dict[str, float]:
    """All-in equity for each starting hand against a random hand.

    Derived from :data:`EQUITY_ORDER`, which lists all 169 starting hands by
    Monte-Carlo all-in equity against a uniformly random opponent.  The position
    in that ordering is a rank, not a probability, so the rank is mapped back
    through the known equity curve rather than reused directly.

    Sampling this instead cost ~3ms on the most common decision in the game;
    reading a table costs nothing.
    """
    total = len(EQUITY_ORDER)
    # ``EQUITY_ORDER[0]`` is AA, so index 0 is the *strongest* hand, not the
    # weakest.  Anchor points read off the real equity curve against a random
    # hand: AA ~85%, the median hand ~51%, the worst ~31%.  Interpolating between
    # them is far more accurate than treating the rank as a probability, which
    # would put AA at 1.0 and 32o at 0.
    anchors = ((0.0, 0.855), (0.10, 0.68), (0.25, 0.60), (0.50, 0.515),
               (0.75, 0.44), (0.90, 0.375), (1.0, 0.315))

    def curve(x: float) -> float:
        for (x0, y0), (x1, y1) in zip(anchors, anchors[1:]):
            if x <= x1:
                span = x1 - x0
                t = 0.0 if span == 0 else (x - x0) / span
                return y0 + (y1 - y0) * t
        return anchors[-1][1]

    return {
        token: curve(index / (total - 1))
        for index, token in enumerate(EQUITY_ORDER)
    }


def _canonical_codes(*groups: list[Card]) -> tuple[str, ...]:
    """Relabel suits by first appearance, so equivalent spots share a key.

    Equity does not depend on *which* suits are involved, only on which cards
    share a suit.  ``Ah Kh`` on ``2h 7d 9c`` is the same problem as ``As Ks`` on
    ``2s 7d 9c``, so both should hit one cache entry.  Without this the cache
    misses on nearly every decision and each miss re-runs the whole simulation.

    The relabelling is applied across the hole cards and the board together, so
    the hole/board suit relationship -- the part that actually matters -- is
    preserved.
    """
    mapping: dict[int, str] = {}
    out: list[str] = []
    for group in groups:
        for card in group:
            if card.suit not in mapping:
                mapping[card.suit] = "shdc"[len(mapping)]
            out.append(f"{card.rank_char}{mapping[card.suit]}")
    return tuple(out)


def equity(hole: list[Card], board: list[Card], *, raising: bool = False) -> float:
    """Chance of winning at showdown against a plausible opponent hand.

    ``raising=True`` narrows the assumed range, because a player who has put in
    a raise is not holding any two cards.  Against a *random* hand nearly every
    holding is near 50%, which would make every pot-odds call look correct, so
    the range matters more than the sampling here.
    """
    if len(hole) != 2 or len(board) > 5:
        return 0.0

    if not board:
        # Pre-flop equity is a property of the two cards alone, and the table is
        # already built from real all-in equity -- no sampling needed.
        base = _preflop_equity_table().get(hand_token(hole) or "", 0.0)
        # Narrower ranges are stronger than random, so shade the number down a
        # little rather than re-simulating.
        return base * (0.93 if raising else 1.0)

    rank = _TIGHT_RANGE_RANK if raising else _STANDARD_RANGE_RANK
    canonical = _canonical_codes(hole, board)
    return _equity_cached(canonical[:2], canonical[2:], rank)


def pot_odds(call_cost: int, pot: int) -> float:
    """The equity needed to break even on a call, as a 0..1 share."""
    if call_cost <= 0:
        return 0.0
    return call_cost / max(1, pot + call_cost)


def hand_label(hole: list[Card], board: list[Card]) -> str:
    """A short description such as ``"One Pair"`` or ``"Ace-high, suited"``."""
    if len(board) >= 3:
        return evaluate(hole + board).name
    if len(hole) != 2:
        return "unknown"
    a, b = hole
    high = RANK_CHARS[max(a.rank, b.rank)]
    low = RANK_CHARS[min(a.rank, b.rank)]
    if a.rank == b.rank:
        return f"Pocket {high}s"
    suited = "suited" if a.suit == b.suit else "offsuit"
    return f"{high}{low} {suited}"


def describe_strength(hole: list[Card], board: list[Card]) -> str:
    value = strength(hole, board)
    label = hand_label(hole, board)
    if value >= 0.9:
        band = "monster"
    elif value >= 0.72:
        band = "very strong"
    elif value >= 0.55:
        band = "strong"
    elif value >= 0.4:
        band = "marginal"
    elif value >= 0.25:
        band = "weak"
    else:
        band = "very weak"
    return f"{label} ({band}, ~{int(value * 100)}th percentile)"


# --- BEGIN GENERATED PREFLOP ORDER ---
#: Every distinct starting hand, strongest first, ranked by Monte-Carlo
#: all-in equity against a uniformly random opponent hand
#: (20000 samples/hand, seed 20240101).
#: Regenerate with: python tools/gen_preflop_ranking.py
EQUITY_ORDER: tuple[str, ...] = (
    "AA", "KK", "QQ", "JJ", "TT", "99", "88", "AKs",
    "77", "AQs", "AJs", "AKo", "AQo", "ATs", "66", "KQs",
    "AJo", "A9s", "ATo", "KJs", "KTs", "A8s", "KJo", "KQo",
    "A9o", "A7s", "A5s", "55", "QJs", "KTo", "A6s", "A8o",
    "K9s", "QTs", "A4s", "A7o", "K8s", "QJo", "K7s", "JTs",
    "Q9s", "A2s", "K9o", "A3s", "A6o", "QTo", "A5o", "44",
    "A4o", "A3o", "K8o", "J9s", "Q8s", "K6s", "Q9o", "A2o",
    "K5s", "K7o", "JTo", "Q7s", "T9s", "K4s", "33", "K3s",
    "K6o", "J9o", "Q6s", "J8s", "Q8o", "K5o", "K2s", "K4o",
    "J7s", "Q5s", "Q7o", "Q4s", "T9o", "T8s", "J8o", "Q6o",
    "K3o", "Q3s", "98s", "Q2s", "T7s", "22", "J6s", "K2o",
    "J7o", "J5s", "Q5o", "T8o", "97s", "T6s", "J4s", "Q4o",
    "98o", "J3s", "T7o", "Q3o", "87s", "J6o", "96s", "Q2o",
    "J5o", "J2s", "T5s", "T6o", "J4o", "T4s", "97o", "86s",
    "76s", "95s", "T3s", "87o", "J3o", "T2s", "85s", "J2o",
    "T5o", "96o", "75s", "94s", "T4o", "65s", "86o", "84s",
    "76o", "93s", "T3o", "95o", "T2o", "92s", "54s", "85o",
    "74s", "64s", "75o", "94o", "83s", "82s", "73s", "65o",
    "93o", "53s", "84o", "92o", "63s", "43s", "72s", "74o",
    "64o", "52s", "54o", "62s", "42s", "83o", "53o", "82o",
    "73o", "32s", "63o", "43o", "72o", "52o", "62o", "42o",
    "32o",
)
# --- END GENERATED PREFLOP ORDER ---
