"""Hand strength helpers shared by the LLM prompt and the offline bot.

Two jobs:

* :func:`preflop_strength` -- a 0..1 percentile for any two hole cards, built on
  a static ordering of all 169 starting hands (Chen-formula scoring).  0.0 is
  7-2 offsuit, 1.0 is pocket aces.
* :func:`postflop_strength` -- a 0..1 estimate from the made-hand category plus
  a little credit for draws.

The LLM does not *need* these numbers -- it reasons for itself -- but they give
it a calibrated anchor, and the offline bot needs them to behave sensibly.
"""

from __future__ import annotations

from functools import lru_cache

from .cards import Card, evaluate

RANK_CHARS = "23456789TJQKA"

# --------------------------------------------------------------------------
# Chen-formula-ish preflop scoring
# --------------------------------------------------------------------------
_HIGH_CARD_VALUE = {
    "A": 10.0,
    "K": 8.0,
    "Q": 7.0,
    "J": 6.0,
    "T": 5.0,
    "9": 4.5,
    "8": 4.0,
    "7": 3.5,
    "6": 3.0,
    "5": 2.5,
    "4": 2.0,
    "3": 1.5,
    "2": 1.0,
}


def _chen_score(high: str, low: str, suited: bool, pair: bool) -> float:
    if pair:
        # Pairs: double the high-card value, minimum 5.
        return max(5.0, _HIGH_CARD_VALUE[high] * 2)

    score = _HIGH_CARD_VALUE[high]
    if suited:
        score += 2.0

    gap = abs(RANK_CHARS.index(high) - RANK_CHARS.index(low)) - 1
    if gap == 1:
        score -= 1.0
    elif gap == 2:
        score -= 2.0
    elif gap == 3:
        score -= 4.0
    elif gap >= 4:
        score -= 5.0

    # Straight bonuses.
    if gap <= 1 and RANK_CHARS.index(high) < RANK_CHARS.index("Q"):
        score += 1.0

    # Round half points up, per the original formula.
    return float(int(score + 0.5)) if score >= 0 else float(-int(-score + 0.5))


@lru_cache(maxsize=1)
def _equity_lookup() -> dict[str, float]:
    """Map a hand token (``"AKs"``/``"72o"``/``"QQ"``) to a 0..1 percentile.

    Sourced from :data:`EQUITY_ORDER`, generated by Monte-Carlo all-in equity
    (see ``tools/gen_preflop_ranking.py``).  Strongest is 1.0, weakest is 0.0.
    """
    total = len(EQUITY_ORDER)
    return {
        token: (total - 1 - index) / (total - 1)
        for index, token in enumerate(EQUITY_ORDER)
    }


def hand_token(hole: list[Card]) -> str | None:
    """Canonical token for two hole cards, e.g. ``"AKs"``, ``"QQ"``, ``"72o"``."""
    if len(hole) != 2:
        return None
    a, b = hole
    if a.rank == b.rank:
        return RANK_CHARS[a.rank] * 2
    high_char = RANK_CHARS[max(a.rank, b.rank)]
    low_char = RANK_CHARS[min(a.rank, b.rank)]
    suffix = "s" if a.suit == b.suit else "o"
    return f"{high_char}{low_char}{suffix}"


def preflop_strength(hole: list[Card]) -> float:
    """0..1 percentile for two hole cards.  1.0 is AA, 0.0 is 32o."""
    token = hand_token(hole)
    if token is None:
        return 0.0
    return _equity_lookup().get(token, 0.0)


# --------------------------------------------------------------------------
# Post-flop strength
# --------------------------------------------------------------------------
# Baseline percentile by made-hand category, refined by how strong the top of
# the hand is.  These are deliberately conservative: one pair is usually not a
# monster multiway.  The spacing keeps the categories strictly ordered after the
# top-rank anchor is applied (see tests/test_strength.py).
_CATEGORY_BASE = {
    "High Card": 0.08,
    "One Pair": 0.36,
    "Two Pair": 0.60,
    "Three of a Kind": 0.76,
    "Straight": 0.86,
    "Flush": 0.93,
    "Full House": 0.965,
    "Four of a Kind": 0.99,
    "Straight Flush": 0.995,
    "Royal Flush": 1.0,
}


def _draw_bonus(hole: list[Card], board: list[Card]) -> float:
    """Small credit for flush and open-ended straight draws."""
    if len(board) < 3 or not hole:
        return 0.0
    bonus = 0.0
    cards = hole + board
    # Four to a flush, with at least one hole card contributing.
    for suit in range(4):
        suited = [c for c in cards if c.suit == suit]
        if len(suited) == 4 and any(c.suit == suit for c in hole):
            bonus += 0.07
            break
    # Four to a straight over a five-rank span.
    ranks = sorted({c.rank for c in cards})
    if 12 in ranks:
        ranks = ranks + [-1]  # ace plays low
    for index in range(len(ranks) - 3):
        window = ranks[index : index + 4]
        if window[-1] - window[0] == 3:
            bonus += 0.05
            break
    return bonus


def postflop_strength(hole: list[Card], board: list[Card]) -> float:
    """0..1 estimate of how good the current made hand is."""
    if len(board) < 3:
        return preflop_strength(hole)
    result = evaluate(hole + board)
    base = _CATEGORY_BASE[result.name]
    # Nudge upward/downward by the strength of the five cards that make it.
    from .cards import best_five

    _, best = best_five(hole + board)
    top_rank = max(card.rank for card in best) / 12 if best else 0.0
    anchor = 0.015 * top_rank
    return min(1.0, base + anchor + _draw_bonus(hole, board))


def strength(hole: list[Card], board: list[Card]) -> float:
    return postflop_strength(hole, board) if len(board) >= 3 else preflop_strength(hole)


def hand_label(hole: list[Card], board: list[Card]) -> str:
    """A short description such as ``"One Pair"`` or ``"Ace-high, suited"``."""
    if len(board) >= 3:
        return evaluate(hole + board).name
    if len(hole) != 2:
        return "unknown"
    a, b = hole
    high = RANK_CHARS[max(a.rank, b.rank)]
    low = RANK_CHARS[min(a.rank, b.rank)]
    if a.rank == b.rank:
        return f"Pocket {high}s"
    suited = "suited" if a.suit == b.suit else "offsuit"
    return f"{high}{low} {suited}"


def describe_strength(hole: list[Card], board: list[Card]) -> str:
    value = strength(hole, board)
    label = hand_label(hole, board)
    if value >= 0.9:
        band = "monster"
    elif value >= 0.72:
        band = "very strong"
    elif value >= 0.55:
        band = "strong"
    elif value >= 0.4:
        band = "marginal"
    elif value >= 0.25:
        band = "weak"
    else:
        band = "very weak"
    return f"{label} ({band}, ~{int(value * 100)}th percentile)"


# --- BEGIN GENERATED PREFLOP ORDER ---
#: Every distinct starting hand, strongest first, ranked by Monte-Carlo
#: all-in equity against a uniformly random opponent hand
#: (20000 samples/hand, seed 20240101).
#: Regenerate with: python tools/gen_preflop_ranking.py
EQUITY_ORDER: tuple[str, ...] = (
    "AA", "KK", "QQ", "JJ", "TT", "99", "88", "AKs",
    "77", "AQs", "AJs", "AKo", "AQo", "ATs", "66", "KQs",
    "AJo", "A9s", "ATo", "KJs", "KTs", "A8s", "KJo", "KQo",
    "A9o", "A7s", "A5s", "55", "QJs", "KTo", "A6s", "A8o",
    "K9s", "QTs", "A4s", "A7o", "K8s", "QJo", "K7s", "JTs",
    "Q9s", "A2s", "K9o", "A3s", "A6o", "QTo", "A5o", "44",
    "A4o", "A3o", "K8o", "J9s", "Q8s", "K6s", "Q9o", "A2o",
    "K5s", "K7o", "JTo", "Q7s", "T9s", "K4s", "33", "K3s",
    "K6o", "J9o", "Q6s", "J8s", "Q8o", "K5o", "K2s", "K4o",
    "J7s", "Q5s", "Q7o", "Q4s", "T9o", "T8s", "J8o", "Q6o",
    "K3o", "Q3s", "98s", "Q2s", "T7s", "22", "J6s", "K2o",
    "J7o", "J5s", "Q5o", "T8o", "97s", "T6s", "J4s", "Q4o",
    "98o", "J3s", "T7o", "Q3o", "87s", "J6o", "96s", "Q2o",
    "J5o", "J2s", "T5s", "T6o", "J4o", "T4s", "97o", "86s",
    "76s", "95s", "T3s", "87o", "J3o", "T2s", "85s", "J2o",
    "T5o", "96o", "75s", "94s", "T4o", "65s", "86o", "84s",
    "76o", "93s", "T3o", "95o", "T2o", "92s", "54s", "85o",
    "74s", "64s", "75o", "94o", "83s", "82s", "73s", "65o",
    "93o", "53s", "84o", "92o", "63s", "43s", "72s", "74o",
    "64o", "52s", "54o", "62s", "42s", "83o", "53o", "82o",
    "73o", "32s", "63o", "43o", "72o", "52o", "62o", "42o",
    "32o",
)
# --- END GENERATED PREFLOP ORDER ---
